name: Simple Workflow

on: 
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run a Linux command
      run: echo "Hello, World!"
