name: Setup MC with Web Access

on:
  workflow_dispatch:

jobs:
  setup-mc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mc nodejs npm

    - name: Setup WebSSH2
      run: |
        git clone https://github.com/billchurch/webssh2.git
        cd webssh2
        npm install

    - name: Start WebSSH2
      run: |
        cd webssh2
        nohup node app.js &  # Запуск WebSSH2 в фоновом режиме
        sleep 30             # Увеличено время ожидания для запуска

    - name: Start Midnight Commander
      run: |
        nohup tmux new-session -d -s mc 'mc' &  # Запуск mc в новой tmux сессии

    - name: Verify WebSSH2
      run: |
        sleep 10  # Дополнительное ожидание для уверенности
        curl -k https://localhost:2222  # Проверка доступности WebSSH2
